### PR TITLE
Added Spanish Language

### PR DESCRIPTION
**Pull request by 1988114**
Added first part of Spanish language translations.

### CODE REVIEW

**Comment by aocneanu** [comment]
Hi,

I will merge this once you will complete the process of adding the new language.

For more info about this read [this](https://docs.laravel-enso.com/packages/localisation.html#new-language) section of the docs.

Thank you for this!

**Comment by aocneanu** [comment]
@1988114 ?

**Comment by 1988114** [comment]
Hello @aocneanu, I Will complete the process today so you can check the pull request.

**Comment by aocneanu** [comment]
@1988114 please read my [comment](https://github.com/laravel-enso/Localisation/pull/52#issuecomment-449947625) from above

**Comment by 1988114** [comment]
Got it mate, will re-submit the full pull request next month, I’ll close this one for now.

**Pull request closed without merging**
