### PR TITLE
Add lang keys

### PR DESCRIPTION
**Pull request by mauthi**
I added new keys with collect function (not finished)
I'm not sure if I should merge translated DE file or all files?

### CODE REVIEW

**Comment by aocneanu** [comment]
Thanks for this!

You should add all DE files and the merge will be done automatically after each comp update if you have in your composer.json file:

```
      "post-update-cmd": [
            "php artisan vendor:publish --force --tag=enso-assets",
            "php artisan vendor:publish --tag=localisation-lang-files",
            "php artisan enso:localisation:merge"
        ]
```

**Comment by mauthi** [comment]
I removed all files except for german file (de.json)
Can you please merge this PR?

**Comment by aocneanu** [comment]
Sorry, I think I misunderstood what you asked initially. Please add the files back.

**Comment by mauthi** [comment]
> will do

so you thought that i am talking of merge command instead of merging PR?

**Comment by mauthi** [comment]
added back the files

**Pull request merged**
