### PR TITLE
Add Arabic Language support

### PR DESCRIPTION
**Pull request by dahabit**
Hi Adrian :)
Thanks for your effort 
I Added Arabic Language support for the default migration seeds & and the Arabic translations files

### CODE REVIEW

**Comment by aocneanu** [comment]
Thank you!

**Comment by aocneanu** [comment]
@dahabit we need a flag also. Help me here:)

**Comment by dahabit** [comment]
@aocneanu Thanks , I already Added "flag-icon-eg" flag [here](https://github.com/laravel-enso/Localisation/pull/21/commits/b1e0af2caae0b9a3dcb24d81c6ad2e3a9e2da68d#diff-5b5da5e4872346f9580febe31d123afc ) and for the image it's [here](https://lipis.github.io/flag-icon-css/flags/4x3/eg.svg)   http://flag-icon-css.lip.is/

I thought the library already have all flags

**Comment by aocneanu** [comment]
Since the latest version only the needed flags are imported instead of the whole lib. The file responsible for flags is https://github.com/laravel-enso/Core/blob/master/src/resources/assets/sass/flags.scss.

The flag is now added.

**Comment by dahabit** [comment]
@aocneanu Great Thanks bro :)

**Pull request merged**
